name: strcolor
description: Flutter package to convert color names to Color in Flutter. Offers a handful way to use colors by their names instead of using Colors constants.
version: 1.1.1
homepage: https://github.com/brworkit/flutter-package-string-to-color

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

